name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Optional: Use GHCR (GitHub Container Registry) instead
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/go-debugger:latest
            ${{ secrets.DOCKER_USERNAME }}/go-debugger:${{ github.sha::0:7 }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/go-debugger:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/go-debugger:buildcache,mode=max

      - name: Show disk usage before cleanup
        run: |
          echo "=== Disk usage before cleanup ==="
          df -h
          docker system df

      - name: Clear Docker and system space
        run: |
          echo "=== Cleaning up Docker resources ==="
          docker system prune -af --volumes
          echo "=== Cleaning up temp files ==="
          sudo rm -rf /tmp/*
          echo "=== Disk usage after cleanup ==="
          df -h
          docker system df
